Repository opentelekomcloud-infra/otc-openapi-schema-validator, pull requests merged in 2025-05, with the labels that each got.

#27 [Feat.] 2.1.9.1 not allowed path params
  public/rulesets/default/2_1_9_Security.yaml
  src/components/Linter.tsx
  src/functions/checkElementSensitiveData.ts
  src/utils/pos.ts
Labels: enhancement, gate

#28 [Feat.] 2.1.9.2 X-Auth-Token header check
  public/rulesets/default/2_1_9_Security.yaml
  src/app/page.tsx
  src/components/RulesetsSelector.tsx
  src/functions/checkParamElementPresence.ts
  src/utils/mapSeverity.ts
Labels: enhancement, gate

#30 [Feat.] 2.1.9.3 allowed methods
  public/rulesets/default/2_1_9_Security.yaml
  src/components/Linter.tsx
  src/components/RulesetsSelector.tsx
  src/functions/allowedMethodCheck.ts
Labels: enhancement, gate

#31 [Feat.] 2.1.10 OAS Compliance rules
  public/rulesets/default/1_2_1_API_Format_Specifications.yaml
  public/rulesets/default/2_1_10_OAS_Compliance.yaml
  src/components/Linter.tsx
  src/functions/checkOASSpec.ts
  src/functions/checkOASVersion.ts
Labels: enhancement, gate

#32 [Fix] Fix selection for only implemented rules
  public/rulesets/default/2_1_7_Compatibility.yaml
  src/components/Linter.tsx
  src/components/RulesetsSelector.tsx
  src/utils/export.ts
Labels: bug, gate

#33 [Fix] Run 1.2.1.2 only if requestBody exist for method
  public/rulesets/default/1_2_1_API_Format_Specifications.yaml
  src/functions/checkParamElementPresence.ts
Labels: gate

#15 Rules for chapter 2.4.1 - GET
  public/rulesets/default/2_4_Request_verb_and_response_status_code.yaml
Labels: gate

#35 [Feat.] Add passed auto rules to reports
  public/rulesets/default/2_4_1_Request_Verb_And_Response_Status_Code.yaml
  src/app/page.tsx
  src/utils/export.ts
Labels: enhancement, gate

#36 [Feat.] Add select/deselect feature for manual rules
  src/components/ManualChecksSelector.tsx
Labels: enhancement, gate
